version: '3.3'

# this is a SAMPLE file. Do not use for build or deployments

# use the following to restrict which OS this is built on
# containerOS: alpine

services:
    postgres:
# build arguments, only needed for building
        build:
            args:
                CBF_VERSION: ${CBF_VERSION:-}
                CG_VERSION: ${CG_VERSION:-7d3d27baf8107b630586c962c057e22149653deb}
                CS_VERSION: ${CS_VERSION:-7d3d27baf8107b630586c962c057e22149653deb}
                POSTGRES_VERSION: ${POSTGRES_VERSION:-10.5}
                QUANTILE_VERSION: ${QUANTILE_VERSION:-1.1.2}
                TIMESCALEDB_VERSION: ${TIMESCALEDB_VERSION:-0.12.1}
                CONTAINER_NAME: postgres
                FROM_BASE: ${DOCKER_REGISTRY:-ubuntu-s2:5000/}${CONTAINER_OS:-alpine}/base_container:${BASE_TAG:-latest}
            cache_from:
                - ${DOCKER_REGISTRY:-ubuntu-s2:5000/}thirdparty/${CONTAINER_OS:-alpine}:${OS_VERSION:-3.8}
                - ${DOCKER_REGISTRY:-ubuntu-s2:5000/}${CONTAINER_OS:-alpine}/base_container:${BASE_TAG:-latest}
            context: .
            dockerfile: Dockerfile
            labels:
                container.build.time: $CONTAINER_BUILD_TIME
                container.fingerprint: $CONTAINER_FINGERPRINT
                container.git.refs: $CONTAINER_GIT_REFS
                container.git.commit: $CONTAINER_GIT_COMMIT
                container.git.url: $CONTAINER_GIT_URL
                container.origin: $CONTAINER_ORIGIN
                container.original.name: postgresql
                version.cbf: $CBF_VERSION
        container_name: postgres
# common arguments, for building and deploy 
        environment:
            DEBUG_TRACE: ${DEBUG_TRACE:-0}
            POSTGRES_PASSWORD_FILE: /run/secrets/postgres.pwd
        hostname: postgres
        image: ${DOCKER_REGISTRY:-ubuntu-s2:5000/}${CONTAINER_OS:-alpine}/postgresql/${POSTGRES_VERSION:-10.5}:${CONTAINER_TAG:-latest}
# deploy arguments, not needed for building
        logging:                              # limit size of logs @runtime so that we do not run out of space 
            driver: json-file
            options:
                max-file: "3"
                max-size: "10m"
        ports:                                #ports exposed 
            - 5432:5432
        restart: unless-stopped               # only use when building a 'service container'
# references to 'secrets' section below
        secrets:
            - postgres.pwd
        volumes:
# startup (load DB) files
            - ./vols-ro/postgres-initdb:/docker-entrypoint-initdb.d
# database files
            - ./vols-rw/data:/var/lib/postgresql/data
# database configuration
            - ./vols-ro/etc:/etc/postgres
# application logs
            - ./vols-rw/log:/var/log/postgres

secrets:
# location of secrets files in host filesystem
   postgres.pwd:
     file: ~/.secrets/postgres.pwd
