version: '3.3'

# repo: https://github/ballab1/postgresql.git
# containerOS: alpine

services:
    postgres:
        build:
            args:
                CBF_VERSION: ${CBF_VERSION:-}
                CG_VERSION: ${CG_VERSION:-7d3d27baf8107b630586c962c057e22149653deb}
                CS_VERSION: ${CS_VERSION:-7d3d27baf8107b630586c962c057e22149653deb}
                POSTGRES_VERSION: ${POSTGRES_VERSION:-10.5}
                QUANTILE_VERSION: ${QUANTILE_VERSION:-1.1.2}
                TIMESCALEDB_VERSION: ${TIMESCALEDB_VERSION:-0.12.1}
                CONTAINER_NAME: postgres
                FROM_BASE: ${DOCKER_REGISTRY:-ubuntu-s2:5000/}${CONTAINER_OS:-alpine}/base_container:${BASE_TAG:-latest}
            cache_from:
                - ${DOCKER_REGISTRY:-ubuntu-s2:5000/}thirdparty/${CONTAINER_OS:-alpine}:${OS_VERSION:-3.8}
                - ${DOCKER_REGISTRY:-ubuntu-s2:5000/}${CONTAINER_OS:-alpine}/base_container:${BASE_TAG:-latest}
            context: .
            dockerfile: Dockerfile
            labels:
                container.build.time: $CONTAINER_BUILD_TIME
                container.fingerprint: $CONTAINER_FINGERPRINT
                container.git.refs: $CONTAINER_GIT_REFS
                container.git.commit: $CONTAINER_GIT_COMMIT
                container.git.url: $CONTAINER_GIT_URL
                container.origin: $CONTAINER_ORIGIN
                container.original.name: postgresql
                container.parent: $CONTAINER_PARENT
                version.cbf: $CBF_VERSION
        container_name: postgres
        environment:
            DEBUG_TRACE: ${DEBUG_TRACE:-0}
            POSTGRES_PASSWORD_FILE: /run/secrets/postgres.pwd
        hostname: postgres
        image: ${DOCKER_REGISTRY:-ubuntu-s2:5000/}${CONTAINER_OS:-alpine}/postgresql/${POSTGRES_VERSION:-12.1}:${CONTAINER_TAG:-latest}
