version: '3.5'

services:
    postgres:
        build:
            args:
                CONTAINER_NAME: postgresql-10.2
                CONTAINER_VERSION: 1.0.7
                DEBUG_TRACE: 0
                FROM_BASE: base_container:${CONTAINER_TAG:-latest}
            context: .
            cache_from:
                - base_container:${CONTAINER_TAG:-latest}
                - alpine:3.6
            context: .
            dockerfile: Dockerfile
        container_name: postgres
        environment:
            DEBUG_TRACE: ${DEBUG_TRACE:-0}
            POSTGRES_PASSWORD: postgres
        hostname: postgres
        image: postgresql-10.3:${CONTAINER_TAG:-latest}
        logging:
            driver: json-file
            options:
                max-file: "3"
                max-size: "10m"
        ports:
            - 5432:5432
#        restart: unless-stopped
        volumes:
            - ./vols-ro/postgres-initdb:/docker-entrypoint-initdb.d
            - ./vols-rw/data:/var/lib/postgresql/data
            - ./vols-ro/etc:/etc/postgres
            - ./vols-rw/log:/var/log/postgres 
