version: '3.5'

services:
    postgres:
        build:
            args:
                FROM_BASE: base_container:20180210
                CONTAINER_VERSION: 1.0.0
            context: .
            cache_from:
                - base_container:20180210
                - alpine:3.6
            context: .
        container_name: postgres
        environment:
            POSTGRES_PASSWORD: postgres
        hostname: postgres
        image: postgresql-10.1:20180210
        logging:
            driver: "json-file"
            options:
                max-size: "10m"
                max-file: "3"
        ports:
            - 5432:5432
        restart: unless-stopped
        volumes:
            - ./vols-ro/postgres-initdb:/docker-entrypoint-initdb.d
            - ./vols-rw/data:/var/lib/postgresql/data
            - ./vols-ro/etc:/etc/postgres
            - ./vols-rw/log:/var/log/postgres 

    base:
        build:
            args:
                FROM_BASE: alpine:3.6
                CONTAINER_VERSION: 1.0.0
                TZ: "America/New_York"
            cache_from:
                - alpine:3.6
            context: ../base_container
        image: base_container:20180210
